"""
Pydantic schemas for Smart B-Roll Inserter
Defines all data structures used across the application
"""

from typing import List, Optional
from pydantic import BaseModel, Field
from enum import Enum


class ProcessingStatus(str, Enum):
    """Status of processing pipeline"""
    PENDING = "pending"
    PROCESSING = "processing"
    COMPLETED = "completed"
    FAILED = "failed"


class TranscriptSegment(BaseModel):
    """A single segment of the A-roll transcript with timestamps"""
    id: int = Field(..., description="Unique identifier for the segment")
    start: float = Field(..., description="Start time in seconds")
    end: float = Field(..., description="End time in seconds")
    text: str = Field(..., description="Transcribed text content")
    
    class Config:
        json_schema_extra = {
            "example": {
                "id": 1,
                "start": 4.2,
                "end": 7.8,
                "text": "This coffee maker gives a rich crema"
            }
        }


class BRollDescription(BaseModel):
    """Description of a B-roll clip generated by vision model"""
    broll_id: str = Field(..., description="Unique identifier for the B-roll clip")
    filename: str = Field(..., description="Original filename of the B-roll")
    description: str = Field(..., description="AI-generated description of the B-roll content")
    duration: float = Field(..., description="Duration of B-roll clip in seconds")
    filepath: str = Field(..., description="Path to the B-roll file")
    
    class Config:
        json_schema_extra = {
            "example": {
                "broll_id": "broll_03",
                "filename": "coffee_pour.mp4",
                "description": "Close-up of coffee pouring into a white ceramic cup with visible golden crema forming on top",
                "duration": 5.2,
                "filepath": "artifacts/uploads/broll/coffee_pour.mp4"
            }
        }


class BRollInsertion(BaseModel):
    """A planned B-roll insertion in the timeline"""
    start_sec: float = Field(..., description="Start time in A-roll to insert B-roll (seconds)")
    duration_sec: float = Field(..., description="Duration of B-roll insertion (seconds)")
    broll_id: str = Field(..., description="ID of the B-roll clip to insert")
    broll_filename: str = Field(..., description="Filename of the B-roll clip")
    confidence: float = Field(..., ge=0, le=1, description="Confidence score of the match (0-1)")
    reason: str = Field(..., description="Explanation of why this B-roll was chosen")
    transcript_segment_id: int = Field(..., description="ID of the transcript segment this relates to")
    transcript_text: str = Field(..., description="The transcript text at this insertion point")
    
    class Config:
        json_schema_extra = {
            "example": {
                "start_sec": 12.5,
                "duration_sec": 2.5,
                "broll_id": "broll_03",
                "broll_filename": "coffee_pour.mp4",
                "confidence": 0.81,
                "reason": "Speaker mentions 'rich crema' which matches the B-roll showing coffee crema close-up",
                "transcript_segment_id": 3,
                "transcript_text": "This coffee maker gives a rich crema"
            }
        }


class TimelinePlan(BaseModel):
    """Complete timeline plan with all B-roll insertions"""
    aroll_filename: str = Field(..., description="Original A-roll filename")
    aroll_duration: float = Field(..., description="Total duration of A-roll in seconds")
    total_insertions: int = Field(..., description="Number of B-roll insertions")
    insertions: List[BRollInsertion] = Field(default_factory=list, description="List of B-roll insertions")
    transcript_segments: List[TranscriptSegment] = Field(default_factory=list, description="Full transcript")
    broll_descriptions: List[BRollDescription] = Field(default_factory=list, description="B-roll descriptions")
    processing_time_sec: Optional[float] = Field(None, description="Total processing time in seconds")
    
    class Config:
        json_schema_extra = {
            "example": {
                "aroll_filename": "talking_head.mp4",
                "aroll_duration": 65.0,
                "total_insertions": 4,
                "insertions": [],
                "transcript_segments": [],
                "broll_descriptions": [],
                "processing_time_sec": 12.5
            }
        }


class UploadResponse(BaseModel):
    """Response after uploading files"""
    success: bool
    message: str
    aroll_filename: Optional[str] = None
    aroll_duration: Optional[float] = None
    broll_files: Optional[List[str]] = None
    broll_count: Optional[int] = None


class TranscriptResponse(BaseModel):
    """Response containing transcript data"""
    success: bool
    message: str
    aroll_filename: str
    duration: float
    segments: List[TranscriptSegment]
    segment_count: int


class BRollCaptionsResponse(BaseModel):
    """Response containing B-roll captions"""
    success: bool
    message: str
    captions: List[BRollDescription]
    caption_count: int


class MatchResult(BaseModel):
    """Result of matching a transcript segment with B-roll options"""
    segment_id: int
    segment_text: str
    segment_start: float
    segment_end: float
    best_broll_id: Optional[str]
    similarity_score: float
    is_suitable: bool
    skip_reason: Optional[str] = None
